//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NfseWsService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="NfseWsService.nfse")]
    public interface nfse
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/CancelarNfseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.CancelarNfseResponse1> CancelarNfseAsync(NfseWsService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorFaixaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorFaixaResponse1> ConsultarNfsePorFaixaAsync(NfseWsService.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfsePorRpsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorRpsResponse1> ConsultarNfsePorRpsAsync(NfseWsService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRpsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsResponse1> RecepcionarLoteRpsAsync(NfseWsService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/GerarNfseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.GerarNfseResponse1> GerarNfseAsync(NfseWsService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="http://nfse.abrasf.org.br/nfse/SubstituirNfseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.SubstituirNfseResponse1> SubstituirNfseAsync(NfseWsService.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="http://nfse.abrasf.org.br/nfse/RecepcionarLoteRpsSincronoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsSincronoResponse1> RecepcionarLoteRpsSincronoAsync(NfseWsService.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarLoteRpsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.ConsultarLoteRpsResponse1> ConsultarLoteRpsAsync(NfseWsService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoPrestadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoPrestadoResponse1> ConsultarNfseServicoPrestadoAsync(NfseWsService.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="http://nfse.abrasf.org.br/nfse/ConsultarNfseServicoTomadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoPrestadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubstituirNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CancelarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GerarNfseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfseServicoTomadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarLoteRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecepcionarLoteRpsSincronoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorRpsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultarNfsePorFaixaResponse))]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoTomadoResponse1> ConsultarNfseServicoTomadoAsync(NfseWsService.ConsultarNfseServicoTomadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class CancelarNfse
    {
        
        private input cancelarNfseRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input CancelarNfseRequest
        {
            get
            {
                return this.cancelarNfseRequestField;
            }
            set
            {
                this.cancelarNfseRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class input
    {
        
        private string nfseCabecMsgField;
        
        private string nfseDadosMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nfseCabecMsg
        {
            get
            {
                return this.nfseCabecMsgField;
            }
            set
            {
                this.nfseCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nfseDadosMsg
        {
            get
            {
                return this.nfseDadosMsgField;
            }
            set
            {
                this.nfseDadosMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfseServicoPrestadoResponse
    {
        
        private output consultarNfseServicoPrestadoResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarNfseServicoPrestadoResponse", Order=0)]
        public output ConsultarNfseServicoPrestadoResponse1
        {
            get
            {
                return this.consultarNfseServicoPrestadoResponse1Field;
            }
            set
            {
                this.consultarNfseServicoPrestadoResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class output
    {
        
        private string outputXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string outputXML
        {
            get
            {
                return this.outputXMLField;
            }
            set
            {
                this.outputXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfseServicoPrestado
    {
        
        private input consultarNfseServicoPrestadoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input ConsultarNfseServicoPrestadoRequest
        {
            get
            {
                return this.consultarNfseServicoPrestadoRequestField;
            }
            set
            {
                this.consultarNfseServicoPrestadoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class SubstituirNfseResponse
    {
        
        private output substituirNfseResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubstituirNfseResponse", Order=0)]
        public output SubstituirNfseResponse1
        {
            get
            {
                return this.substituirNfseResponse1Field;
            }
            set
            {
                this.substituirNfseResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class SubstituirNfse
    {
        
        private input substituirNfseRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input SubstituirNfseRequest
        {
            get
            {
                return this.substituirNfseRequestField;
            }
            set
            {
                this.substituirNfseRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class CancelarNfseResponse
    {
        
        private output cancelarNfseResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CancelarNfseResponse", Order=0)]
        public output CancelarNfseResponse1
        {
            get
            {
                return this.cancelarNfseResponse1Field;
            }
            set
            {
                this.cancelarNfseResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class GerarNfseResponse
    {
        
        private output gerarNfseResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GerarNfseResponse", Order=0)]
        public output GerarNfseResponse1
        {
            get
            {
                return this.gerarNfseResponse1Field;
            }
            set
            {
                this.gerarNfseResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class GerarNfse
    {
        
        private input gerarNfseRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input GerarNfseRequest
        {
            get
            {
                return this.gerarNfseRequestField;
            }
            set
            {
                this.gerarNfseRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class RecepcionarLoteRpsResponse
    {
        
        private output recepcionarLoteRpsResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecepcionarLoteRpsResponse", Order=0)]
        public output RecepcionarLoteRpsResponse1
        {
            get
            {
                return this.recepcionarLoteRpsResponse1Field;
            }
            set
            {
                this.recepcionarLoteRpsResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class RecepcionarLoteRps
    {
        
        private input recepcionarLoteRpsRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input RecepcionarLoteRpsRequest
        {
            get
            {
                return this.recepcionarLoteRpsRequestField;
            }
            set
            {
                this.recepcionarLoteRpsRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfseServicoTomadoResponse
    {
        
        private output consultarNfseServicoTomadoResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarNfseServicoTomadoResponse", Order=0)]
        public output ConsultarNfseServicoTomadoResponse1
        {
            get
            {
                return this.consultarNfseServicoTomadoResponse1Field;
            }
            set
            {
                this.consultarNfseServicoTomadoResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfseServicoTomado
    {
        
        private input consultarNfseServicoTomadoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input ConsultarNfseServicoTomadoRequest
        {
            get
            {
                return this.consultarNfseServicoTomadoRequestField;
            }
            set
            {
                this.consultarNfseServicoTomadoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarLoteRpsResponse
    {
        
        private output consultarLoteRpsResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarLoteRpsResponse", Order=0)]
        public output ConsultarLoteRpsResponse1
        {
            get
            {
                return this.consultarLoteRpsResponse1Field;
            }
            set
            {
                this.consultarLoteRpsResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarLoteRps
    {
        
        private input consultarLoteRpsRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input ConsultarLoteRpsRequest
        {
            get
            {
                return this.consultarLoteRpsRequestField;
            }
            set
            {
                this.consultarLoteRpsRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class RecepcionarLoteRpsSincronoResponse
    {
        
        private output recepcionarLoteRpsSincronoResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecepcionarLoteRpsSincronoResponse", Order=0)]
        public output RecepcionarLoteRpsSincronoResponse1
        {
            get
            {
                return this.recepcionarLoteRpsSincronoResponse1Field;
            }
            set
            {
                this.recepcionarLoteRpsSincronoResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class RecepcionarLoteRpsSincrono
    {
        
        private input recepcionarLoteRpsSincronoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input RecepcionarLoteRpsSincronoRequest
        {
            get
            {
                return this.recepcionarLoteRpsSincronoRequestField;
            }
            set
            {
                this.recepcionarLoteRpsSincronoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        private output consultarNfsePorRpsResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarNfsePorRpsResponse", Order=0)]
        public output ConsultarNfsePorRpsResponse1
        {
            get
            {
                return this.consultarNfsePorRpsResponse1Field;
            }
            set
            {
                this.consultarNfsePorRpsResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfsePorRps
    {
        
        private input consultarNfsePorRpsRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input ConsultarNfsePorRpsRequest
        {
            get
            {
                return this.consultarNfsePorRpsRequestField;
            }
            set
            {
                this.consultarNfsePorRpsRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfsePorFaixaResponse
    {
        
        private output consultarNfsePorFaixaResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarNfsePorFaixaResponse", Order=0)]
        public output ConsultarNfsePorFaixaResponse1
        {
            get
            {
                return this.consultarNfsePorFaixaResponse1Field;
            }
            set
            {
                this.consultarNfsePorFaixaResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nfse.abrasf.org.br")]
    public partial class ConsultarNfsePorFaixa
    {
        
        private input consultarNfsePorFaixaRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public input ConsultarNfsePorFaixaRequest
        {
            get
            {
                return this.consultarNfsePorFaixaRequestField;
            }
            set
            {
                this.consultarNfsePorFaixaRequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.CancelarNfse CancelarNfse;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(NfseWsService.CancelarNfse CancelarNfse)
        {
            this.CancelarNfse = CancelarNfse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object CancelarNfseResponse;
        
        public CancelarNfseResponse1()
        {
        }
        
        public CancelarNfseResponse1(object CancelarNfseResponse)
        {
            this.CancelarNfseResponse = CancelarNfseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorFaixaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.ConsultarNfsePorFaixa ConsultarNfsePorFaixa;
        
        public ConsultarNfsePorFaixaRequest()
        {
        }
        
        public ConsultarNfsePorFaixaRequest(NfseWsService.ConsultarNfsePorFaixa ConsultarNfsePorFaixa)
        {
            this.ConsultarNfsePorFaixa = ConsultarNfsePorFaixa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorFaixaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ConsultarNfsePorFaixaResponse;
        
        public ConsultarNfsePorFaixaResponse1()
        {
        }
        
        public ConsultarNfsePorFaixaResponse1(object ConsultarNfsePorFaixaResponse)
        {
            this.ConsultarNfsePorFaixaResponse = ConsultarNfsePorFaixaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.ConsultarNfsePorRps ConsultarNfsePorRps;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(NfseWsService.ConsultarNfsePorRps ConsultarNfsePorRps)
        {
            this.ConsultarNfsePorRps = ConsultarNfsePorRps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ConsultarNfsePorRpsResponse;
        
        public ConsultarNfsePorRpsResponse1()
        {
        }
        
        public ConsultarNfsePorRpsResponse1(object ConsultarNfsePorRpsResponse)
        {
            this.ConsultarNfsePorRpsResponse = ConsultarNfsePorRpsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.RecepcionarLoteRps RecepcionarLoteRps;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(NfseWsService.RecepcionarLoteRps RecepcionarLoteRps)
        {
            this.RecepcionarLoteRps = RecepcionarLoteRps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object RecepcionarLoteRpsResponse;
        
        public RecepcionarLoteRpsResponse1()
        {
        }
        
        public RecepcionarLoteRpsResponse1(object RecepcionarLoteRpsResponse)
        {
            this.RecepcionarLoteRpsResponse = RecepcionarLoteRpsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.GerarNfse GerarNfse;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(NfseWsService.GerarNfse GerarNfse)
        {
            this.GerarNfse = GerarNfse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object GerarNfseResponse;
        
        public GerarNfseResponse1()
        {
        }
        
        public GerarNfseResponse1(object GerarNfseResponse)
        {
            this.GerarNfseResponse = GerarNfseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.SubstituirNfse SubstituirNfse;
        
        public SubstituirNfseRequest()
        {
        }
        
        public SubstituirNfseRequest(NfseWsService.SubstituirNfse SubstituirNfse)
        {
            this.SubstituirNfse = SubstituirNfse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object SubstituirNfseResponse;
        
        public SubstituirNfseResponse1()
        {
        }
        
        public SubstituirNfseResponse1(object SubstituirNfseResponse)
        {
            this.SubstituirNfseResponse = SubstituirNfseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.RecepcionarLoteRpsSincrono RecepcionarLoteRpsSincrono;
        
        public RecepcionarLoteRpsSincronoRequest()
        {
        }
        
        public RecepcionarLoteRpsSincronoRequest(NfseWsService.RecepcionarLoteRpsSincrono RecepcionarLoteRpsSincrono)
        {
            this.RecepcionarLoteRpsSincrono = RecepcionarLoteRpsSincrono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object RecepcionarLoteRpsSincronoResponse;
        
        public RecepcionarLoteRpsSincronoResponse1()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponse1(object RecepcionarLoteRpsSincronoResponse)
        {
            this.RecepcionarLoteRpsSincronoResponse = RecepcionarLoteRpsSincronoResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.ConsultarLoteRps ConsultarLoteRps;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(NfseWsService.ConsultarLoteRps ConsultarLoteRps)
        {
            this.ConsultarLoteRps = ConsultarLoteRps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ConsultarLoteRpsResponse;
        
        public ConsultarLoteRpsResponse1()
        {
        }
        
        public ConsultarLoteRpsResponse1(object ConsultarLoteRpsResponse)
        {
            this.ConsultarLoteRpsResponse = ConsultarLoteRpsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.ConsultarNfseServicoPrestado ConsultarNfseServicoPrestado;
        
        public ConsultarNfseServicoPrestadoRequest()
        {
        }
        
        public ConsultarNfseServicoPrestadoRequest(NfseWsService.ConsultarNfseServicoPrestado ConsultarNfseServicoPrestado)
        {
            this.ConsultarNfseServicoPrestado = ConsultarNfseServicoPrestado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ConsultarNfseServicoPrestadoResponse;
        
        public ConsultarNfseServicoPrestadoResponse1()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponse1(object ConsultarNfseServicoPrestadoResponse)
        {
            this.ConsultarNfseServicoPrestadoResponse = ConsultarNfseServicoPrestadoResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        public NfseWsService.ConsultarNfseServicoTomado ConsultarNfseServicoTomado;
        
        public ConsultarNfseServicoTomadoRequest()
        {
        }
        
        public ConsultarNfseServicoTomadoRequest(NfseWsService.ConsultarNfseServicoTomado ConsultarNfseServicoTomado)
        {
            this.ConsultarNfseServicoTomado = ConsultarNfseServicoTomado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nfse.abrasf.org.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ConsultarNfseServicoTomadoResponse;
        
        public ConsultarNfseServicoTomadoResponse1()
        {
        }
        
        public ConsultarNfseServicoTomadoResponse1(object ConsultarNfseServicoTomadoResponse)
        {
            this.ConsultarNfseServicoTomadoResponse = ConsultarNfseServicoTomadoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface nfseChannel : NfseWsService.nfse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<NfseWsService.nfse>, NfseWsService.nfse
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public nfseClient() : 
                base(nfseClient.GetDefaultBinding(), nfseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.nfseSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), nfseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.CancelarNfseResponse1> NfseWsService.nfse.CancelarNfseAsync(NfseWsService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.CancelarNfseResponse1> CancelarNfseAsync(NfseWsService.CancelarNfse CancelarNfse)
        {
            NfseWsService.CancelarNfseRequest inValue = new NfseWsService.CancelarNfseRequest();
            inValue.CancelarNfse = CancelarNfse;
            return ((NfseWsService.nfse)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorFaixaResponse1> NfseWsService.nfse.ConsultarNfsePorFaixaAsync(NfseWsService.ConsultarNfsePorFaixaRequest request)
        {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorFaixaResponse1> ConsultarNfsePorFaixaAsync(NfseWsService.ConsultarNfsePorFaixa ConsultarNfsePorFaixa)
        {
            NfseWsService.ConsultarNfsePorFaixaRequest inValue = new NfseWsService.ConsultarNfsePorFaixaRequest();
            inValue.ConsultarNfsePorFaixa = ConsultarNfsePorFaixa;
            return ((NfseWsService.nfse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorRpsResponse1> NfseWsService.nfse.ConsultarNfsePorRpsAsync(NfseWsService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.ConsultarNfsePorRpsResponse1> ConsultarNfsePorRpsAsync(NfseWsService.ConsultarNfsePorRps ConsultarNfsePorRps)
        {
            NfseWsService.ConsultarNfsePorRpsRequest inValue = new NfseWsService.ConsultarNfsePorRpsRequest();
            inValue.ConsultarNfsePorRps = ConsultarNfsePorRps;
            return ((NfseWsService.nfse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsResponse1> NfseWsService.nfse.RecepcionarLoteRpsAsync(NfseWsService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsResponse1> RecepcionarLoteRpsAsync(NfseWsService.RecepcionarLoteRps RecepcionarLoteRps)
        {
            NfseWsService.RecepcionarLoteRpsRequest inValue = new NfseWsService.RecepcionarLoteRpsRequest();
            inValue.RecepcionarLoteRps = RecepcionarLoteRps;
            return ((NfseWsService.nfse)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.GerarNfseResponse1> NfseWsService.nfse.GerarNfseAsync(NfseWsService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.GerarNfseResponse1> GerarNfseAsync(NfseWsService.GerarNfse GerarNfse)
        {
            NfseWsService.GerarNfseRequest inValue = new NfseWsService.GerarNfseRequest();
            inValue.GerarNfse = GerarNfse;
            return ((NfseWsService.nfse)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.SubstituirNfseResponse1> NfseWsService.nfse.SubstituirNfseAsync(NfseWsService.SubstituirNfseRequest request)
        {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.SubstituirNfseResponse1> SubstituirNfseAsync(NfseWsService.SubstituirNfse SubstituirNfse)
        {
            NfseWsService.SubstituirNfseRequest inValue = new NfseWsService.SubstituirNfseRequest();
            inValue.SubstituirNfse = SubstituirNfse;
            return ((NfseWsService.nfse)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsSincronoResponse1> NfseWsService.nfse.RecepcionarLoteRpsSincronoAsync(NfseWsService.RecepcionarLoteRpsSincronoRequest request)
        {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.RecepcionarLoteRpsSincronoResponse1> RecepcionarLoteRpsSincronoAsync(NfseWsService.RecepcionarLoteRpsSincrono RecepcionarLoteRpsSincrono)
        {
            NfseWsService.RecepcionarLoteRpsSincronoRequest inValue = new NfseWsService.RecepcionarLoteRpsSincronoRequest();
            inValue.RecepcionarLoteRpsSincrono = RecepcionarLoteRpsSincrono;
            return ((NfseWsService.nfse)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.ConsultarLoteRpsResponse1> NfseWsService.nfse.ConsultarLoteRpsAsync(NfseWsService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.ConsultarLoteRpsResponse1> ConsultarLoteRpsAsync(NfseWsService.ConsultarLoteRps ConsultarLoteRps)
        {
            NfseWsService.ConsultarLoteRpsRequest inValue = new NfseWsService.ConsultarLoteRpsRequest();
            inValue.ConsultarLoteRps = ConsultarLoteRps;
            return ((NfseWsService.nfse)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoPrestadoResponse1> NfseWsService.nfse.ConsultarNfseServicoPrestadoAsync(NfseWsService.ConsultarNfseServicoPrestadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoPrestadoResponse1> ConsultarNfseServicoPrestadoAsync(NfseWsService.ConsultarNfseServicoPrestado ConsultarNfseServicoPrestado)
        {
            NfseWsService.ConsultarNfseServicoPrestadoRequest inValue = new NfseWsService.ConsultarNfseServicoPrestadoRequest();
            inValue.ConsultarNfseServicoPrestado = ConsultarNfseServicoPrestado;
            return ((NfseWsService.nfse)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoTomadoResponse1> NfseWsService.nfse.ConsultarNfseServicoTomadoAsync(NfseWsService.ConsultarNfseServicoTomadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseWsService.ConsultarNfseServicoTomadoResponse1> ConsultarNfseServicoTomadoAsync(NfseWsService.ConsultarNfseServicoTomado ConsultarNfseServicoTomado)
        {
            NfseWsService.ConsultarNfseServicoTomadoRequest inValue = new NfseWsService.ConsultarNfseServicoTomadoRequest();
            inValue.ConsultarNfseServicoTomado = ConsultarNfseServicoTomado;
            return ((NfseWsService.nfse)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://es-aracruz-pm-nfs-backend.cloud.el.com.br/producao24/NfseWSService");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return nfseClient.GetBindingForEndpoint(EndpointConfiguration.nfseSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return nfseClient.GetEndpointAddress(EndpointConfiguration.nfseSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            nfseSOAP,
        }
    }
}
