//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotafiscalService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd", ConfigurationName="NotafiscalService.NotaFiscalServiceSoap")]
    public interface NotaFiscalServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(NotafiscalService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(NotafiscalService.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.GerarNfseResponse> GerarNfseAsync(NotafiscalService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.CancelarNfseResponse> CancelarNfseAsync(NotafiscalService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/SubstituirNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.SubstituirNfseResponse> SubstituirNfseAsync(NotafiscalService.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(NotafiscalService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(NotafiscalService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/ConsultarNfseServicoPrestado", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(NotafiscalService.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/ConsultarNfseServicoTomado", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(NotafiscalService.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.abrasf.org.br/nfse.xsd/ConsultarNfseFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseFaixaResponse> ConsultarNfseFaixaAsync(NotafiscalService.ConsultarNfseFaixaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRps", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.RecepcionarLoteRpsRequestBody Body;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(NotafiscalService.RecepcionarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class RecepcionarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public RecepcionarLoteRpsRequestBody()
        {
        }
        
        public RecepcionarLoteRpsRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.RecepcionarLoteRpsResponseBody Body;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(NotafiscalService.RecepcionarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class RecepcionarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecepcionarLoteRpsResult;
        
        public RecepcionarLoteRpsResponseBody()
        {
        }
        
        public RecepcionarLoteRpsResponseBody(string RecepcionarLoteRpsResult)
        {
            this.RecepcionarLoteRpsResult = RecepcionarLoteRpsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsSincrono", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.RecepcionarLoteRpsSincronoRequestBody Body;
        
        public RecepcionarLoteRpsSincronoRequest()
        {
        }
        
        public RecepcionarLoteRpsSincronoRequest(NotafiscalService.RecepcionarLoteRpsSincronoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class RecepcionarLoteRpsSincronoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public RecepcionarLoteRpsSincronoRequestBody()
        {
        }
        
        public RecepcionarLoteRpsSincronoRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsSincronoResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.RecepcionarLoteRpsSincronoResponseBody Body;
        
        public RecepcionarLoteRpsSincronoResponse()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponse(NotafiscalService.RecepcionarLoteRpsSincronoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class RecepcionarLoteRpsSincronoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecepcionarLoteRpsSincronoResult;
        
        public RecepcionarLoteRpsSincronoResponseBody()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponseBody(string RecepcionarLoteRpsSincronoResult)
        {
            this.RecepcionarLoteRpsSincronoResult = RecepcionarLoteRpsSincronoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.GerarNfseRequestBody Body;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(NotafiscalService.GerarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class GerarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public GerarNfseRequestBody()
        {
        }
        
        public GerarNfseRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfseResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.GerarNfseResponseBody Body;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(NotafiscalService.GerarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class GerarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GerarNfseResult;
        
        public GerarNfseResponseBody()
        {
        }
        
        public GerarNfseResponseBody(string GerarNfseResult)
        {
            this.GerarNfseResult = GerarNfseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.CancelarNfseRequestBody Body;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(NotafiscalService.CancelarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class CancelarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public CancelarNfseRequestBody()
        {
        }
        
        public CancelarNfseRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfseResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.CancelarNfseResponseBody Body;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(NotafiscalService.CancelarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class CancelarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelarNfseResult;
        
        public CancelarNfseResponseBody()
        {
        }
        
        public CancelarNfseResponseBody(string CancelarNfseResult)
        {
            this.CancelarNfseResult = CancelarNfseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNfse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.SubstituirNfseRequestBody Body;
        
        public SubstituirNfseRequest()
        {
        }
        
        public SubstituirNfseRequest(NotafiscalService.SubstituirNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class SubstituirNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public SubstituirNfseRequestBody()
        {
        }
        
        public SubstituirNfseRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNfseResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.SubstituirNfseResponseBody Body;
        
        public SubstituirNfseResponse()
        {
        }
        
        public SubstituirNfseResponse(NotafiscalService.SubstituirNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class SubstituirNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubstituirNfseResult;
        
        public SubstituirNfseResponseBody()
        {
        }
        
        public SubstituirNfseResponseBody(string SubstituirNfseResult)
        {
            this.SubstituirNfseResult = SubstituirNfseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRps", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarLoteRpsRequestBody Body;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(NotafiscalService.ConsultarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public ConsultarLoteRpsRequestBody()
        {
        }
        
        public ConsultarLoteRpsRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRpsResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarLoteRpsResponseBody Body;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(NotafiscalService.ConsultarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarLoteRpsResult;
        
        public ConsultarLoteRpsResponseBody()
        {
        }
        
        public ConsultarLoteRpsResponseBody(string ConsultarLoteRpsResult)
        {
            this.ConsultarLoteRpsResult = ConsultarLoteRpsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRps", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfsePorRpsRequestBody Body;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(NotafiscalService.ConsultarNfsePorRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfsePorRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public ConsultarNfsePorRpsRequestBody()
        {
        }
        
        public ConsultarNfsePorRpsRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRpsResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfsePorRpsResponseBody Body;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(NotafiscalService.ConsultarNfsePorRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfsePorRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarNfsePorRpsResult;
        
        public ConsultarNfsePorRpsResponseBody()
        {
        }
        
        public ConsultarNfsePorRpsResponseBody(string ConsultarNfsePorRpsResult)
        {
            this.ConsultarNfsePorRpsResult = ConsultarNfsePorRpsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoPrestado", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseServicoPrestadoRequestBody Body;
        
        public ConsultarNfseServicoPrestadoRequest()
        {
        }
        
        public ConsultarNfseServicoPrestadoRequest(NotafiscalService.ConsultarNfseServicoPrestadoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseServicoPrestadoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public ConsultarNfseServicoPrestadoRequestBody()
        {
        }
        
        public ConsultarNfseServicoPrestadoRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoPrestadoResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseServicoPrestadoResponseBody Body;
        
        public ConsultarNfseServicoPrestadoResponse()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponse(NotafiscalService.ConsultarNfseServicoPrestadoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseServicoPrestadoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarNfseServicoPrestadoResult;
        
        public ConsultarNfseServicoPrestadoResponseBody()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponseBody(string ConsultarNfseServicoPrestadoResult)
        {
            this.ConsultarNfseServicoPrestadoResult = ConsultarNfseServicoPrestadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoTomado", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseServicoTomadoRequestBody Body;
        
        public ConsultarNfseServicoTomadoRequest()
        {
        }
        
        public ConsultarNfseServicoTomadoRequest(NotafiscalService.ConsultarNfseServicoTomadoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseServicoTomadoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public ConsultarNfseServicoTomadoRequestBody()
        {
        }
        
        public ConsultarNfseServicoTomadoRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoTomadoResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseServicoTomadoResponseBody Body;
        
        public ConsultarNfseServicoTomadoResponse()
        {
        }
        
        public ConsultarNfseServicoTomadoResponse(NotafiscalService.ConsultarNfseServicoTomadoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseServicoTomadoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarNfseServicoTomadoResult;
        
        public ConsultarNfseServicoTomadoResponseBody()
        {
        }
        
        public ConsultarNfseServicoTomadoResponseBody(string ConsultarNfseServicoTomadoResult)
        {
            this.ConsultarNfseServicoTomadoResult = ConsultarNfseServicoTomadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseFaixaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseFaixa", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseFaixaRequestBody Body;
        
        public ConsultarNfseFaixaRequest()
        {
        }
        
        public ConsultarNfseFaixaRequest(NotafiscalService.ConsultarNfseFaixaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseFaixaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensagemXML;
        
        public ConsultarNfseFaixaRequestBody()
        {
        }
        
        public ConsultarNfseFaixaRequestBody(string mensagemXML)
        {
            this.mensagemXML = mensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseFaixaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseFaixaResponse", Namespace="http://www.abrasf.org.br/nfse.xsd", Order=0)]
        public NotafiscalService.ConsultarNfseFaixaResponseBody Body;
        
        public ConsultarNfseFaixaResponse()
        {
        }
        
        public ConsultarNfseFaixaResponse(NotafiscalService.ConsultarNfseFaixaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.abrasf.org.br/nfse.xsd")]
    public partial class ConsultarNfseFaixaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarNfseFaixaResult;
        
        public ConsultarNfseFaixaResponseBody()
        {
        }
        
        public ConsultarNfseFaixaResponseBody(string ConsultarNfseFaixaResult)
        {
            this.ConsultarNfseFaixaResult = ConsultarNfseFaixaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface NotaFiscalServiceSoapChannel : NotafiscalService.NotaFiscalServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NotaFiscalServiceSoapClient : System.ServiceModel.ClientBase<NotafiscalService.NotaFiscalServiceSoap>, NotafiscalService.NotaFiscalServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotaFiscalServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NotaFiscalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), NotaFiscalServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotaFiscalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotaFiscalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsResponse> NotafiscalService.NotaFiscalServiceSoap.RecepcionarLoteRpsAsync(NotafiscalService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string mensagemXML)
        {
            NotafiscalService.RecepcionarLoteRpsRequest inValue = new NotafiscalService.RecepcionarLoteRpsRequest();
            inValue.Body = new NotafiscalService.RecepcionarLoteRpsRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsSincronoResponse> NotafiscalService.NotaFiscalServiceSoap.RecepcionarLoteRpsSincronoAsync(NotafiscalService.RecepcionarLoteRpsSincronoRequest request)
        {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string mensagemXML)
        {
            NotafiscalService.RecepcionarLoteRpsSincronoRequest inValue = new NotafiscalService.RecepcionarLoteRpsSincronoRequest();
            inValue.Body = new NotafiscalService.RecepcionarLoteRpsSincronoRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.GerarNfseResponse> NotafiscalService.NotaFiscalServiceSoap.GerarNfseAsync(NotafiscalService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.GerarNfseResponse> GerarNfseAsync(string mensagemXML)
        {
            NotafiscalService.GerarNfseRequest inValue = new NotafiscalService.GerarNfseRequest();
            inValue.Body = new NotafiscalService.GerarNfseRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.CancelarNfseResponse> NotafiscalService.NotaFiscalServiceSoap.CancelarNfseAsync(NotafiscalService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.CancelarNfseResponse> CancelarNfseAsync(string mensagemXML)
        {
            NotafiscalService.CancelarNfseRequest inValue = new NotafiscalService.CancelarNfseRequest();
            inValue.Body = new NotafiscalService.CancelarNfseRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.SubstituirNfseResponse> NotafiscalService.NotaFiscalServiceSoap.SubstituirNfseAsync(NotafiscalService.SubstituirNfseRequest request)
        {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.SubstituirNfseResponse> SubstituirNfseAsync(string mensagemXML)
        {
            NotafiscalService.SubstituirNfseRequest inValue = new NotafiscalService.SubstituirNfseRequest();
            inValue.Body = new NotafiscalService.SubstituirNfseRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarLoteRpsResponse> NotafiscalService.NotaFiscalServiceSoap.ConsultarLoteRpsAsync(NotafiscalService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string mensagemXML)
        {
            NotafiscalService.ConsultarLoteRpsRequest inValue = new NotafiscalService.ConsultarLoteRpsRequest();
            inValue.Body = new NotafiscalService.ConsultarLoteRpsRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfsePorRpsResponse> NotafiscalService.NotaFiscalServiceSoap.ConsultarNfsePorRpsAsync(NotafiscalService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string mensagemXML)
        {
            NotafiscalService.ConsultarNfsePorRpsRequest inValue = new NotafiscalService.ConsultarNfsePorRpsRequest();
            inValue.Body = new NotafiscalService.ConsultarNfsePorRpsRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoPrestadoResponse> NotafiscalService.NotaFiscalServiceSoap.ConsultarNfseServicoPrestadoAsync(NotafiscalService.ConsultarNfseServicoPrestadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string mensagemXML)
        {
            NotafiscalService.ConsultarNfseServicoPrestadoRequest inValue = new NotafiscalService.ConsultarNfseServicoPrestadoRequest();
            inValue.Body = new NotafiscalService.ConsultarNfseServicoPrestadoRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoTomadoResponse> NotafiscalService.NotaFiscalServiceSoap.ConsultarNfseServicoTomadoAsync(NotafiscalService.ConsultarNfseServicoTomadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string mensagemXML)
        {
            NotafiscalService.ConsultarNfseServicoTomadoRequest inValue = new NotafiscalService.ConsultarNfseServicoTomadoRequest();
            inValue.Body = new NotafiscalService.ConsultarNfseServicoTomadoRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseFaixaResponse> NotafiscalService.NotaFiscalServiceSoap.ConsultarNfseFaixaAsync(NotafiscalService.ConsultarNfseFaixaRequest request)
        {
            return base.Channel.ConsultarNfseFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotafiscalService.ConsultarNfseFaixaResponse> ConsultarNfseFaixaAsync(string mensagemXML)
        {
            NotafiscalService.ConsultarNfseFaixaRequest inValue = new NotafiscalService.ConsultarNfseFaixaRequest();
            inValue.Body = new NotafiscalService.ConsultarNfseFaixaRequestBody();
            inValue.Body.mensagemXML = mensagemXML;
            return ((NotafiscalService.NotaFiscalServiceSoap)(this)).ConsultarNfseFaixaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotaFiscalServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NotaFiscalServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotaFiscalServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnfse.vitoria.es.gov.br/producao/NotaFiscalService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NotaFiscalServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsnfse.vitoria.es.gov.br/producao/NotaFiscalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NotaFiscalServiceSoap,
            
            NotaFiscalServiceSoap12,
        }
    }
}
